name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Trigger only for main
  pull_request:
    branches:
      - main  # Optional: Trigger on PRs to main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        platform: [linux/amd64, linux/arm64]  # Multi-platform support

    steps:
      # Checkout the repository code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build and push Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: ${{ matrix.platform }}  # Use matrix for platforms
          push: true
          tags: |
            krunal233/blog.krunalakbari.in:latest
            krunal233/blog.krunalakbari.in:${{ github.sha }}
          build-args: |
            GIT_SHA=${{ github.sha }}
            BUILD_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          labels: |
            org.opencontainers.image.source=${{ github.repository }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.created=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
